# Generated by Django 3.1.5 on 2021-01-25 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='제목', max_length=50)),
                ('text', models.TextField(db_column='내용', help_text='메모 내용은 150자 이내로 입력가능합니다.', max_length=150)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('priority', models.BooleanField(db_column='중요도')),
                ('name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
