# Generated by Django 3.1.5 on 2021-01-26 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memoapp', '0002_memos_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memos',
            name='likes',
            field=models.ManyToManyField(default='admin', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
